export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER_USER_START = 'AUTH_REGISTER_USER_START';
export const AUTH_REGISTER_USER_FAIL = 'AUTH_REGISTER_USER_FAIL';
export const SET_MAIN_USER_START = 'SET_MAIN_USER';
export const SET_MAIN_USER_SUCCESS = 'SET_MAIN_USER_SUCCESS';
